# Generated by Django 3.1 on 2020-08-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='username',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='nickname',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
