# Generated by Django 3.1 on 2020-08-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200829_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='nickname',
            new_name='username',
        ),
    ]
